language: node_js
node_js:
  - 8

before_deploy: npm run build

deploy:
  - provider: s3
    aws_access_key_id: $AWS_ACCESS_KEY_ID
    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'out-of-school-time'
    upload-dir: 'prod'
    on:
      branch: master
    local_dir: dist
    skip_cleanup: true
  - provider: s3
    aws_access_key_id: $AWS_ACCESS_KEY_ID
    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'out-of-school-time'
    upload-dir: 'staging'
    on:
      branch: staging
    local_dir: dist
    skip_cleanup: true

